# Generated by Django 3.1.4 on 2021-01-02 05:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201231_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 2, 5, 11, 49, 729127, tzinfo=utc)),
        ),
    ]
